name: build
on:
  push:
    branches: ['main']

jobs:
  container-job:
    runs-on: ubuntu-22.04
    container:
      image: node:18.14.2-alpine3.17
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y --force-yes p7zip-full language-pack-zh-han*
          echo $LANG
          export LANG="zh_CN.UTF-8"
          wget https://github.com/banned-historical-archives/banned-historical-archives10/raw/master/7z/1946%E5%B9%B405%E6%9C%88.7z
          ls
